table_column_mapping = {
    'metalicity': 'M_H',
    'temperature': 'TEFF',
    'surface_gravity': 'LOGG',
    'vsini': 'VSINI',
    'vmicro': 'VMICRO',
    'vmacro': 'VMACRO',
    'j_error': 'J_ERR',
    'h_error': 'H_ERR',
    'k_error': 'K_ERR',
}

to_remove_from_main_dataset = ['P_FE_ERR',
                                       'P_FE_FLAG',
                                       'CU_FE_ERR', 'GAIAEDR3_PARALLAX_ERROR', 'GAIAEDR3_PMRA', 'GAIAEDR3_PMRA_ERROR',
                                       'GAIAEDR3_PMDEC', 'GAIAEDR3_PMDEC_ERROR', 'GAIAEDR3_PHOT_G_MEAN_MAG',
                                       'GAIAEDR3_PHOT_BP_MEAN_MAG', 'GAIAEDR3_PHOT_RP_MEAN_MAG',
                                       'GAIAEDR3_DR2_RADIAL_VELOCITY', 'GAIAEDR3_DR2_RADIAL_VELOCITY_ERROR',
                                       'GAIAEDR3_R_MED_GEO', 'GAIAEDR3_R_LO_GEO', 'GAIAEDR3_R_HI_GEO',
                                       'GAIAEDR3_R_MED_PHOTOGEO', 'GAIAEDR3_R_LO_PHOTOGEO',
                                       'GAIAEDR3_R_HI_PHOTOGEO', 'MEANFIB', 'SIGFIB', 'AK_TARG', 'AK_TARG_METHOD',
                                       'APOGEE_TARGET1', 'APOGEE_TARGET2', 'APOGEE2_TARGET1',
                                       'APOGEE2_TARGET2', 'APOGEE2_TARGET3', 'APOGEE2_TARGET4',
                                       'RV_CHI2', 'RV_CCFWHM', 'RV_AUTOFWHM', 'VSCATTER', 'VERR', 'RV_FEH', 'RV_FLAG',
                                       'MIN_H', 'MAX_H',
                                       'MIN_JK', 'MAX_JK', 'GAIAEDR3_SOURCE_ID', 'GAIAEDR3_PARALLAX',
                                       'ASPCAP_GRID', 'ASPCAP_CHI2', 'FRAC_LOWSNR', 'FRAC_SIGSKY',
                                       'ELEM_CHI2', 'ELEMFRAC', 'EXTRATARG', 'MEMBERFLAG', 'MEMBER', 'X_H_SPEC',
                                       'X_M_SPEC', 'STARFLAG', 'ANDFLAG', 'ASPCAPFLAG', 'TARGFLAGS', 'PARAMFLAG',
                                       'FRAC_BADPIX', 'FRAC_LOWSNR', 'FRAC_SIGSKY', 'ELEM_CHI2', 'ELEMFRAC',
                                       'X_H_SPEC', 'X_M_SPEC', 'TEFF_SPEC', 'LOGG_SPEC', 'CU_FE_FLAG', 'ALT_ID',
                                       'PROGRAMNAME',
                                       'RV_TEFF', 'RV_LOGG', 'RV_ALPHA', 'RV_CARB', 'SNREV', 'SFD_EBV', 'N_COMPONENTS']

to_remove_from_chemicals = ['RV_FEH', 'MIN_H', 'MAX_H', 'GAIAEDR3_R_HI_GEO', 'GAIAEDR3_R_HI_PHOTOGEO',
                            'CU_FE_ERR',
                            'P_FE_ERR', 'P_FE_FLAG',
                            'CU_FE_FLAG',
                            'M_H', 'M_H_ERR', 'X_H_SPEC', 'X_H', 'X_H_ERR']


# const.py

CHEMICAL_ELEMENTS_DATA = {
    'C': {
        'name': 'Carbon',
        'symbol': 'C',
        'atomic_number': 6,
        'electronic_configuration': '1s2 2s2 2p2',
        'period': 2,
        'family': 'Nonmetal',
    },
    'CI': {
        'name': 'Carbon I',
        'symbol': 'C I',
        'atomic_number': 6,
        'electronic_configuration': '1s2 2s2 2p2',
        'period': 2,
        'family': 'Nonmetal',
    },
    'N': {
        'name': 'Nitrogen',
        'symbol': 'N',
        'atomic_number': 7,
        'electronic_configuration': '1s2 2s2 2p3',
        'period': 2,
        'family': 'Nonmetal',
    },
    'O': {
        'name': 'Oxygen',
        'symbol': 'O',
        'atomic_number': 8,
        'electronic_configuration': '1s2 2s2 2p4',
        'period': 2,
        'family': 'Nonmetal',
    },
    'NA': {
        'name': 'Sodium',
        'symbol': 'Na',
        'atomic_number': 11,
        'electronic_configuration': '[Ne] 3s1',
        'period': 3,
        'family': 'Alkali metal',
    },
    'MG': {
        'name': 'Magnesium',
        'symbol': 'Mg',
        'atomic_number': 12,
        'electronic_configuration': '[Ne] 3s2',
        'period': 3,
        'family': 'Alkaline earth metal',
    },
    'AL': {
        'name': 'Aluminum',
        'symbol': 'Al',
        'atomic_number': 13,
        'electronic_configuration': '[Ne] 3s2 3p1',
        'period': 3,
        'family': 'Post-transition metal',
    },
    'SI': {
        'name': 'Silicon',
        'symbol': 'Si',
        'atomic_number': 14,
        'electronic_configuration': '[Ne] 3s2 3p2',
        'period': 3,
        'family': 'Metalloid',
    },
    'S': {
        'name': 'Sulfur',
        'symbol': 'S',
        'atomic_number': 16,
        'electronic_configuration': '[Ne] 3s2 3p4',
        'period': 3,
        'family': 'Nonmetal',
    },
    'K': {
        'name': 'Potassium',
        'symbol': 'K',
        'atomic_number': 19,
        'electronic_configuration': '[Ar] 4s1',
        'period': 4,
        'family': 'Alkali metal',
    },
    'CA': {
        'name': 'Calcium',
        'symbol': 'Ca',
        'atomic_number': 20,
        'electronic_configuration': '[Ar] 4s2',
        'period': 4,
        'family': 'Alkaline earth metal',
    },
    'TI': {
        'name': 'Titanium',
        'symbol': 'Ti',
        'atomic_number': 22,
        'electronic_configuration': '[Ar] 3d2 4s2',
        'period': 4,
        'family': 'Transition metal',
    },
    'TIII': {
        'name': 'Titanium III',
        'symbol': 'Ti III',
        'atomic_number': 22,
        'electronic_configuration': '[Ar] 3d1 4s2',
        'period': 4,
        'family': 'Transition metal',
    },
    'V': {
        'name': 'Vanadium',
        'symbol': 'V',
        'atomic_number': 23,
        'electronic_configuration': '[Ar] 3d3 4s2',
        'period': 4,
        'family': 'Transition metal',
    },
    'CR': {
        'name': 'Chromium',
        'symbol': 'Cr',
        'atomic_number': 24,
        'electronic_configuration': '[Ar] 3d5 4s1',
        'period': 4,
        'family': 'Transition metal',
    },
    'MN': {
        'name': 'Manganese',
        'symbol': 'Mn',
        'atomic_number': 25,
        'electronic_configuration': '[Ar] 3d5 4s2',
        'period': 4,
        'family': 'Transition metal',
    },
    'CO': {
        'name': 'Cobalt',
        'symbol': 'Co',
        'atomic_number': 27,
        'electronic_configuration': '[Ar] 3d7 4s2',
        'period': 4,
        'family': 'Transition metal',
    },
    'NI': {
        'name': 'Nickel',
        'symbol': 'Ni',
        'atomic_number': 28,
        'electronic_configuration': '[Ar] 3d8 4s2',
        'period': 4,
        'family': 'Transition metal',
    },
    'CE': {
        'name': 'Cerium',
        'symbol': 'Ce',
        'atomic_number': 58,
        'electronic_configuration': '[Xe] 4f1 5d1 6s2',
        'period': 6,
        'family': 'Lanthanide',
    },
    'FE': {
        'name': 'Iron',
        'symbol': 'Fe',
        'atomic_number': 26,
        'electronic_configuration': '[Ar] 3d6 4s2',
        'period': 4,
        'family': 'Transition metal',
    },
}
